clc;
audio = audioread('guitar.wav');
disp(audioinfo('guitar.wav'));
d = 200;
num = [zeros(d,1); 1]';
den = 1;
signal = filter(num, den, audio);
%sound(audio);
sound(signal);
figure; 
plot(audio(1:20000)); 
hold;
plot(signal(1:20000));
